# Generated by Django 3.0.8 on 2020-10-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_customer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='profile/logo.png', null=True, upload_to='profile'),
        ),
    ]
