# Generated by Django 3.0.8 on 2020-10-14 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('display_pic', models.ImageField(blank=True, default='gallery1.png', null=True, upload_to='')),
                ('content', models.TextField()),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date_published'],
            },
        ),
    ]
